- include: "{{ ansible_os_family }}.yml"
  tags: keepalived
  become: yes

- name: copy keepalived config
  template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
    mode: 0600
  notify:
    - restart keepalived
  tags: keepalived
  become: yes

- name: enable keepalived service
  service:
    name: keepalived
    state: started
    enabled: yes
  tags: keepalived
  become: yes